INSERT INTO ARTICLE(TITLE, CONTENT, CREATED_AT, UPDATED_AT, AUTHOR) VALUES('제목 1', '내용 1', NOW(), NOW(), 'Admin')
INSERT INTO ARTICLE(TITLE, CONTENT, CREATED_AT, UPDATED_AT, AUTHOR) VALUES('제목 2', '내용 2', NOW(), NOW(), 'Admin')
INSERT INTO ARTICLE(TITLE, CONTENT, CREATED_AT, UPDATED_AT, AUTHOR) VALUES('제목 3', '내용 3', NOW(), NOW(), 'Admin')